version: '3.8'

services:
  weather-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-mcp-server
    ports:
      - "${HOST_PORT:-8000}:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: ${RESTART_POLICY:-unless-stopped}
