services:
  weather_agent:
    build:
      context: ./aip_agent_quickstart/agents/weather_agent
      dockerfile: Dockerfile
    container_name: weather_agent_service
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  weather_mcp_server:
    build:
      context: ./aip_agent_quickstart/mcp_server_docker/weather_forecast
      dockerfile: Dockerfile
    container_name: weather_mcp_server
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: ${RESTART_POLICY:-unless-stopped}

  weather_adk_agent:
    build:
      context: ./aip_agent_quickstart/agents/weather_adk_agent
      dockerfile: Dockerfile
    container_name: weather_adk_agent_service
    ports:
      - "8004:8004"
    restart: unless-stopped
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
