version: '3.8'

services:
  weather_agent:
    build:
      context: ./aip_agent_quickstart/agents/weather_agent
      dockerfile: Dockerfile
    container_name: weather_agent_service
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # volumes:
    #   - ./aip_agent_quickstart/agents/weather_agent:/usr/src/app # Optional: for live code reloading during development


# You can define shared networks or volumes here if needed
# networks:
#   agents_network:
#     driver: bridge
