version: '3.8'

services:
  weather_agent:
    build:
      context: ./aip_agent_quickstart/agents/weather_agent
      dockerfile: Dockerfile
    container_name: weather_agent_service
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  travel_advisor_agent:
    build:
      context: ./aip_agent_quickstart/agents/travel_advisor_agent
      dockerfile: Dockerfile
    container_name: travel_advisor_agent_service
    ports:
      - "8002:8002"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}


# You can define shared networks or volumes here if needed
# networks:
#   agents_network:
#     driver: bridge
