services:
  weather_agent:
    build:
      context: ./aip_agent_quickstart/agents/weather_agent
      dockerfile: Dockerfile
    container_name: weather_agent_service
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  arxiv_mcp_server:
    build:
      context: ./aip_agent_quickstart/mcp_servers/arxiv
      dockerfile: Dockerfile
    container_name: arxiv_mcp_server
    ports:
      - "8006:8006"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: ${RESTART_POLICY:-unless-stopped}
