"""Defines the __init__ for the config package."""

from .agent import (
    ARXIV_AGENT_INSTRUCTION,
    CALCULATOR_AGENT_INSTRUCTION,
    COORDINATOR_MULTI_AGENT_INSTRUCTION,
    DEFAULT_AGENT_INSTRUCTION,
    MATH_AGENT_INSTRUCTION,
    WEATHER_AGENT_INSTRUCTION,
)

__all__ = [
    "DEFAULT_AGENT_INSTRUCTION",
    "CALCULATOR_AGENT_INSTRUCTION",
    "WEATHER_AGENT_INSTRUCTION",
    "MATH_AGENT_INSTRUCTION",
    "COORDINATOR_MULTI_AGENT_INSTRUCTION",
    "ARXIV_AGENT_INSTRUCTION",
]
