[tool.poetry]
name = "simple-pipeline"
version = "0.0.1"
description = ""
authors = ["GenAI SDK Team <gat-sdk@gdplabs.id>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
gllm-pipeline-binary = {version="*"}
gllm-core-binary = {version="*"}
gllm-plugin-binary = {version="*"}
gllm-generation-binary = {version="*"}
gllm-rag-binary = {version="*"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
